name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: Ubuntu 20.04.3 LTS
    steps:
      - name: Print greeting
        run: echo "Hello World!"
      - name: Print goodbye
        run: echo "Done - bye!"
